# Official framework image. Look for the different tagged releases at: https://hub.docker.com/r/library/node/tags/
variables:
  CONFIG_PACKAGE_NAME: sif-cli
  RUSH_PARALLELISM: 8
  APP_CONFIG_DIR: common/build/configdir
  BRANCH: main
  ENVIRONMENT: staging
  AWS_REGION: us-west-2

.prod-variables: &prod-variables
  ENVIRONMENT: production
  AWS_REGION: us-west-2

.main-run-condition: &main-run-condition
  - if: ($CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE != /.*\[skip ci\].*/ && $CI_PIPELINE_SOURCE != "schedule")

.common-build-steps: &common-build-steps # install dependencies
  - pushd ${CI_PROJECT_DIR}/
  - npm install
  - popd


.common-install-dependencies: &common-install-dependencies
  - uname -r
  - yum install -y amazon-linux-extras
  - amazon-linux-extras install epel -y
  - yum update -y
  - yum install p7zip git tar perl-Digest-SHA xz sudo -y
  - cp /usr/bin/7za /usr/bin/7z

.common-artifacts: &common-artifacts
  artifacts:
    paths:
      - dist/*.tar.*
      - dist/macos/*

.dependabot:
  image:
    name: docker.io/andrcuns/dependabot-gitlab:0.11.0
    entrypoint: [ "" ]
  variables:
    GIT_STRATEGY: none
    PACKAGE_MANAGER: $CI_JOB_NAME
    RAILS_ENV: production
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__STANDALONE: "true"
  before_script:
    - cd /home/dependabot/app
  script:
    - bundle exec rake "dependabot:update[$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME,$PACKAGE_MANAGER,/]"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "dependabot"'

stages:
  - dependency_check
  - package

default:
  tags:
    - arch:amd64
    - size:large
  image:
    name: public.ecr.aws/lambda/nodejs:18
    entrypoint: [ '' ]
  before_script:
    - *common-install-dependencies

npm:
  stage: dependency_check
  extends: .dependabot

package:
  image:
    name: public.ecr.aws/lambda/nodejs:18
    entrypoint: [ '' ]
  before_script:
    - *common-install-dependencies
  rules:
    - *main-run-condition
  stage: package
  variables:
    <<: *prod-variables
  script:
    - *common-build-steps
    - pushd ${CI_PROJECT_DIR}/
    - npm run package:tarballs
    - ls dist
  artifacts:
    paths:
      - dist/sif-*-linux-x64.tar.gz
