name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    uses: oclif/github-workflows/.github/workflows/automerge.yml@main
    secrets: inherit
